# Generated by Django 5.2.4 on 2025-07-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_productos/'),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='datecompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
