# Generated by Django 5.2.4 on 2025-07-08 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_servicios_imagen_alter_servicios_datecompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
