# Generated by Django 5.2.4 on 2025-07-08 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_servicios_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicios',
            name='datecompleted',
        ),
    ]
