# Generated by Django 5.2.4 on 2025-07-08 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_remove_servicios_datecompleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicios',
            name='important',
        ),
    ]
